//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinav.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimizda
    {
        public int PersonelId { get; set; }
        public string isim { get; set; }
        public string görev { get; set; }
        public string aciklama { get; set; }
        public string resim { get; set; }
    }
}
