//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinav.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ozellik
    {
        public int id { get; set; }
        public string icon { get; set; }
        public string açiklama { get; set; }
        public string butonrenk { get; set; }
    }
}
