// <auto-generated />
using FluentApiilTabloOlusturma.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FluentApiilTabloOlusturma.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.Firma", b =>
                {
                    b.Property<int>("Anahtar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FirmaUnvan");

                    b.HasKey("Anahtar");

                    b.ToTable("Tbl_Firma");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.Personel", b =>
                {
                    b.Property<int>("Anahtar_Personel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyisim")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Soyad");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TelefonNumara");

                    b.Property<int>("firID")
                        .HasColumnType("int");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ad");

                    b.HasKey("Anahtar_Personel");

                    b.HasIndex("firID");

                    b.ToTable("Tbl_Personel");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.ProductDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prtID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("prtID")
                        .IsUnique();

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.Suplier", b =>
                {
                    b.Property<int>("SuplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuplierID");

                    b.ToTable("Supliers");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.SuplierProduct", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "SupplierID");

                    b.HasIndex("SupplierID");

                    b.ToTable("SuplierProducts");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.Personel", b =>
                {
                    b.HasOne("FluentApiilTabloOlusturma.Models.Firma", "Firma")
                        .WithMany("personeller")
                        .HasForeignKey("firID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.ProductDetails", b =>
                {
                    b.HasOne("FluentApiilTabloOlusturma.Models.Product", "Product")
                        .WithOne("ProductDetails")
                        .HasForeignKey("FluentApiilTabloOlusturma.Models.ProductDetails", "prtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.SuplierProduct", b =>
                {
                    b.HasOne("FluentApiilTabloOlusturma.Models.Product", "Product")
                        .WithMany("SuplierProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluentApiilTabloOlusturma.Models.Suplier", "Suplier")
                        .WithMany("SuplierProducts")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Suplier");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.Firma", b =>
                {
                    b.Navigation("personeller");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.Product", b =>
                {
                    b.Navigation("ProductDetails");

                    b.Navigation("SuplierProducts");
                });

            modelBuilder.Entity("FluentApiilTabloOlusturma.Models.Suplier", b =>
                {
                    b.Navigation("SuplierProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
